name: SEPHSbiome CI Workflow

# Trigger the workflow on push or pull request to any branch
on: [push, pull_request]

jobs:
  # Python Linting
  lint-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Ensure this matches your project's Python version
    - name: Install Python dependencies
      run: pip install flake8 # Add any other necessary packages
    - name: Lint Python code
      run: flake8 .

  # Docker Build
  build-docker:
    runs-on: ubuntu-latest
    needs: lint-python
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        username: SephAros
        password: ${{ secrets.SEPHSDISC }}
    - name: Build and push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sepharos/sephsbiome:${{ github.sha }}
        file: ./Docker/Dockerfile # Adjusted to point to the Dockerfile in the Docker folder
        context: . # The context is set to the current directory

